on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Collect version
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          TAG=${GITHUB_REF#refs/*/}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Compress script
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./src
          outPath: homebrew-awspm-${{ env.TAG }}-darwin-arm64.tar.gz
      - name: Release artifact
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.TAG }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: homebrew-awspm-${{ env.TAG }}-darwin-arm64.tar.gz
          asset_name: homebrew-awspm-${{ env.VERSION }}-darwin-arm64.tar.gz
          asset_content_type: application/gzip
      - name: Release artifact for Homebrew
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: spryfox-analytics
          homebrew_tap: homebrew-awspm
          formula_folder: formula
          github_token: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
          commit_owner: Maximilian Walther
          commit_email: maximilian.walther@spryfox.de
          depends_on: |
            "bash" => :build
          install: 'bin.install "awspm.sh" => "awspm"'
          # Custom test command for your formula so you can run `brew test`.
          # Optional - string.
          # test: 'assert_match("my script output", shell_output("my-script-command"))'
          target_darwin_amd64: false
          target_darwin_arm64: true
          target_linux_amd64: false
          target_linux_arm64: false
          skip_commit: false
          debug: false
